title: Kokopelli
description: Kokopelli Plant Medicine
baseurl: ''
url: 'https://kokopelli.ie'
ogimage: 'https://placehold.co/1200x630'

contacts:
    instagram: 'https://www.instagram.com/kokopelli_plant_medicine/'
    whatsapp: '#'

development: false

author:
    name: Rytis Nefiodovas
    email: rytisnefiodovas@icloud.com

markdown: kramdown
source: src

plugins:
    - jekyll-feed
    - jekyll-seo-tag
    - jekyll-sitemap
    - jekyll-paginate-v2
    - jekyll-sass-converter

pagination:
    enabled: true
    per_page: 10
    permalink: 'page/:num/'

sass:
    style: compressed
    sass_dir: _sass

collections:
    products:
        output: true
        permalink: /products/:name/
        template: product
    categories:
        output: false
        permalink: /category/:name/
